service:
  name: kaskadi-update-ysws-stocks-lambda

package:
  individually: true
  exclude:
    - "**/**"

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket
  apiGateway:
    restApiId: !ImportValue KaskadiStocksRestAPIGatewayId
    restApiRootResourceId: !ImportValue KaskadiStocksRestAPIGatewayRootResourceId
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: 'arn:aws:lambda:eu-central-1:374163881813:function:kaskadi-set-stocks-lambda' # not using export/import logic to avoid coupling of stack which could cause troubles with deployment in that case

layers:
  KaskadiStockUpdateLayer:
    path: layer
    name: ${self:service.name}-layer
    description: Layer for ${self:service.name}
    compatibleRuntimes:
      - nodejs10.x
      - nodejs12.x
    licenseInfo: MIT
    package:
      include:
        - '**/**'

functions:
  KaskadiStockUpdate:
    handler: kaskadi-update-ysws-stocks-lambda.handler
    name: ${self:service.name}
    layers:
      - { Ref: KaskadiStockUpdateLayerLambdaLayer }
    package:
      include:
        - 'kaskadi-update-ysws-stocks-lambda.js'
    environment:
      WEMALO_TOKEN: ${env:WEMALO_TOKEN}
      ES_ID: ${env:ES_ID}
      ES_SECRET: ${env:ES_SECRET}
      ES_ENDPOINT: ${env:ES_ENDPOINT}
    events:
      - http:
          method: get
          path: ysws/update
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !ImportValue KaskadiStocksCognitoAuthorizerId
      - schedule:
          rate: cron(55 6 ? * MON *) # runs every monday at 6:55AM
          enabled: true
